services:
  grafana-export-to-pdf:
    build: 
      context: .
      target: development
    volumes:
      - ./src:/usr/src/app/src
      - ./output:/usr/src/app/output
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG_MODE=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "${EXPORT_SERVER_PORT:-3001}:${EXPORT_SERVER_PORT:-3001}"
    command: npm run dev 